version: '3.3'

services:
  cfhqd-bot:
    container_name: cfhqd-bot
    build: .
    restart: always
    env_file:
      - .env

  cfhqd-database:
    container_name: cfhqd-database
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5439:5439"
    expose:
      - "5439"
    command: -p 5439
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${POSTGRES_USER}" ]
      timeout: 5s
      interval: 1s
      retries: 10
  
volumes:
  postgres_data:

networks:
  default:
    name: bridge-nerwork 
    external: true
